const ADD_NFT_METADATA = 'ADD_NFT_METADATA'
const ADD_NFT_METADATA_SUCCESS = 'ADD_NFT_METADATA_SUCCESS'
const ADD_NFT_METADATA_ERROR = 'ADD_NFT_METADATA_ERROR'
const HIDE_ERROR = 'HIDE_ERROR'

export {
  ADD_NFT_METADATA,
  ADD_NFT_METADATA_SUCCESS,
  ADD_NFT_METADATA_ERROR,
  HIDE_ERROR,
}
